### ISSUE TITLE
Which API Version?

### ISSUE THREAD

**Issue by XedinUnknown** [idealo/idealo-orders-api-php-sdk#6]
Hi!

It appears that there is a [v2.0 of the order API][order-api-2.0] now. Which version of the API is this SDK for? I couldn't find that in the readme.

[order-api-2.0]: https://cdn.idealo.com/folder/Direktkauf/documentation/merchant-order-api-v2.html

**Comment by rr2002** [comment]
Hello,

please excuse the late reply. The SDK only supports the V1. And then only an older version of the V1. We have not updated the project for some time. It is also unclear whether idealo wants to update the sources to the newer version. The code can only be used as an "insperation".  I am very sorry that I have no better news at the moment.

Robert

idealo
